#!/bin/bash

LOCUST_MODE=${LOCUST_MODE:="standalone"}
LOCUST_MASTER=${LOCUST_MASTER:=""}
LOCUST_LOCUSTFILE_PATH=${LOCUST_LOCUSTFILE_PATH:="/app/locustfile.py"}
LOCUST_LOCUSTFILE_URL=${LOCUST_LOCUSTFILE_URL:=""}
LOCUST_TARGET_HOST=${LOCUST_TARGET_HOST:="https://example.com"}

if [ ! -z "$LOCUST_LOCUSTFILE_URL" ]; then
    LOCUST_LOCUSTFILE_PATH="/app/locustfile.py"
    curl $LOCUST_LOCUSTFILE_URL -o $LOCUST_LOCUSTFILE_PATH
fi

LOCUST_PATH="poetry run locust"
LOCUST_FLAGS="-f $LOCUST_LOCUSTFILE_PATH --host=$LOCUST_TARGET_HOST"

if [[ "$LOCUST_MODE" = "master" ]]; then
    LOCUST_FLAGS="$LOCUST_FLAGS --master"
elif [[ "$LOCUST_MODE" = "worker" ]]; then
    LOCUST_FLAGS="$LOCUST_FLAGS --worker --master-host=$LOCUST_MASTER"
fi

exec $LOCUST_PATH $LOCUST_FLAGS